{
 "title": "My test dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "description": "Test to show host memory",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_Active_bytes" }
   ]
  },
  {
   "title": "Total CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "targets": [
    { "expr": "sum(cpu_usage)" }
   ]
  },
  {
   "title": "Average cpu usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 9 },
   "targets": [
    { "expr": "avg(cpu_usage)" }
   ]
  },
  {
   "title": "Top 10 cpu usage processes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "topk(10,cpu_usage)", "legendFormat": "{{process}} {{pid}}" }
   ]
  }
 ]
}