# https://finestructure.co/blog/2016/5/16/monitoring-with-prometheus-grafana-docker-part-1
version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus_data:/prometheus
    ports:
        - '9090:9090'

  node-exporter:
        image: prom/node-exporter:latest
        ports:
            - '9100:9100'

  pushgateway:
        image: prom/pushgateway:latest
        ports:
            - '9091:9091'

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
    prometheus_data: {}
    grafana_data: {}